"""Plan-aware optimization utilities for fine-tuning."""

from ._protocols import FineTunePlanProtocol, GroupSpecProtocol, PyTree
from .adalora import (
    AdaLoRAController,
    AdaLoRAState,
    allocate_rank_mask,
    make_adalora_controller,
)
from .averaging import AveragingState
from .builders import (
    adamw8_from_plan,
    adamw_from_plan,
    compile_optimizer,
    estimate_optimizer_state,
    hybrid_aurora_adam_from_plan,
    hybrid_kron_adam_from_plan,
    hybrid_prism_adam_from_plan,
    optimizer_from_plan,
    schedule_free_adam_from_plan,
)
from .config import (
    AccumulationConfig,
    AdaLoRAControllerConfig,
    CompiledGroup,
    EMAConfig,
    GradientPolicy,
    GroupRule,
    OptimizerBundle,
    OptimizerConfig,
    OptimizerReport,
    PlanGroup,
    PrecisionConfig,
    SAMConfig,
    SCHEMA_VERSION,
    SWAConfig,
    ScheduleConfig,
    SchedulePoint,
    StateQuantizationConfig,
)
from .diagnostics import (
    OptimizerStateMemoryEstimate,
    OptimizerStateMemorySummary,
    StateLeafSummary,
    estimate_optimizer_state_memory,
    optimizer_state_memory_summary,
)
from .groups import compile_groups, matches_rule, preview_groups
from .recipes import (
    FineTuneOptimizerRecipe,
    adapters_adamw,
    bitfit_adamw,
    full_ft_adamw,
    linear_probe_adamw,
    lora_adamw,
    partial_ft_adamw,
    prompts_adamw,
)
from .schedules import build_schedule, preview_schedule
from .serialization import (
    OptimizerStateCheckpoint,
    OptimizerStateRestoreError,
    load_state_checkpoint,
    make_state_checkpoint,
    restore_state_checkpoint,
    save_state_checkpoint,
    state_manifest,
)
from .state_migration import (
    CounterPolicy,
    OptimizerMigrationReport,
    StatePolicy,
    reconfigure_optimizer,
)
from .step import (
    SAMStepInfo,
    make_plan_update_step,
    make_sam_step,
    make_update_step,
    sam_cost_report,
)
from .validation import NormalizedPlan, plan_fingerprint, validate_plan


__all__ = (
    "SCHEMA_VERSION",
    "AccumulationConfig",
    "AdaLoRAControllerConfig",
    "AdaLoRAController",
    "AdaLoRAState",
    "AveragingState",
    "CompiledGroup",
    "CounterPolicy",
    "EMAConfig",
    "FineTuneOptimizerRecipe",
    "FineTunePlanProtocol",
    "GradientPolicy",
    "GroupRule",
    "GroupSpecProtocol",
    "NormalizedPlan",
    "OptimizerBundle",
    "OptimizerConfig",
    "OptimizerReport",
    "OptimizerStateCheckpoint",
    "OptimizerStateRestoreError",
    "OptimizerMigrationReport",
    "OptimizerStateMemorySummary",
    "OptimizerStateMemoryEstimate",
    "PlanGroup",
    "PrecisionConfig",
    "PyTree",
    "SAMConfig",
    "SAMStepInfo",
    "SWAConfig",
    "ScheduleConfig",
    "SchedulePoint",
    "StateQuantizationConfig",
    "StatePolicy",
    "StateLeafSummary",
    "adapters_adamw",
    "allocate_rank_mask",
    "adamw8_from_plan",
    "adamw_from_plan",
    "bitfit_adamw",
    "build_schedule",
    "compile_groups",
    "compile_optimizer",
    "estimate_optimizer_state",
    "estimate_optimizer_state_memory",
    "full_ft_adamw",
    "hybrid_aurora_adam_from_plan",
    "hybrid_kron_adam_from_plan",
    "hybrid_prism_adam_from_plan",
    "linear_probe_adamw",
    "load_state_checkpoint",
    "lora_adamw",
    "make_plan_update_step",
    "make_adalora_controller",
    "make_sam_step",
    "make_state_checkpoint",
    "make_update_step",
    "matches_rule",
    "optimizer_from_plan",
    "optimizer_state_memory_summary",
    "partial_ft_adamw",
    "plan_fingerprint",
    "preview_groups",
    "preview_schedule",
    "prompts_adamw",
    "reconfigure_optimizer",
    "restore_state_checkpoint",
    "save_state_checkpoint",
    "schedule_free_adam_from_plan",
    "sam_cost_report",
    "state_manifest",
    "validate_plan",
)
